# -*- coding: utf-8 -*-
"""pandas_lecture_extra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSPu0UIhOxQ-kBzAQgMs-uNKCAyjxl4L
"""

'''
Matplot
  -> Use for Visualization, Automation

'''

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

'''
1. Bar plot : One categorical column vs one numerical column
2. Scatter plot : one numerical column vs one numerical column
3. Pie chart : one categorical column vs one numerical column : Distribution
4. Line chart : one numerical column vs one numerical column : Trend
'''

'''
Matplotlib.pyplot method:
1. plot() -> plots graph
2. xlabel() -> x axis label
3. ylabel() -> y axis label
4. title() -> title of graph
5. grid() -> grid line
6. show() -> show the graph
7. ylim(0,max_number_limit) -> y axis limit
'''

'''

'''

year=[2000,2001,2002,2003,2004,2005]
sales=[10000,20000,40000,60000,80000,90000]

plt.plot(year,sales)
plt.xlabel('Year')
plt.ylabel('Sales')
plt.title('Sales vs Year : Sales Trend Analysis')
plt.grid()
plt.ylim(0,100000)
plt.show()

year=[2000,2001,2002,2003,2004,2005]
sales_Q1=[10000,20000,40000,60000,80000,90000]
sales_Q2=[12000,8000,9200,62000,82000,92000]

plt.plot(year,sales_Q1,linestyle='--',marker='*',color='r')
plt.plot(year,sales_Q2,linestyle='--',marker='.',color='b')
plt.axhline(50000,color='g',)
plt.xlabel('Year')
plt.ylabel('sales')
plt.grid()
plt.title('Trend analysis')
plt.show()

plt.boxplot([sales_Q1])
plt.ylabel('Sales')
plt.title('Box plot showing Outliers')
plt.show()

data=np.array([1,3,5,7,9,10,15,1000,2000,5000,-89])
df=pd.Series(data)
print(df.skew())
plt.boxplot(data)
plt.show()

'''
why impute with medians :
  -> graph shifts towards origin
'''

plt.figure(figsize=(5,5))
plt.pie(x=sales_Q1,labels=year,
        autopct='%0.2f',
        explode=[0.01,0.01,0.01,0.01,0.01,0.09])

plt.title('Sales Pie')

plt.show()

plt.bar(year,sales_Q1,color='lightblue',width=0.5,edgecolor='r')
plt.plot(year,sales_Q1,color='red',marker='*',linestyle='--')
plt.show()

plt.scatter(sales_Q1,sales_Q2,color='r')
plt.plot(sales_Q1,sales_Q2,linestyle='--')
plt.xlabel('Sales Q1')
plt.ylabel('Sales Q2')
plt.title('Scatter plot')
plt.grid()
plt.show()

