# -*- coding: utf-8 -*-
"""Pandas_lecture6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z6UqX4ycEh8CgL4ZB8n0bdAykpy79Lao
"""

# Lecture 6
# Matplot seaborn and subplots

# importing Data Manipulation lib

import numpy as np
import pandas as pd

# importing data visualization lib

import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/titanic_dataset.csv')
df.head()

plt.bar(df['Embarked'],df['Pclass'],color='gray')
plt.title('Bar Plot')
plt.xlabel('Embarked')
plt.ylabel('Class')
plt.show()

# using Seaborn
sns.barplot(data=df,x='Embarked',y='Pclass',color='green')
# sns.barplot(x=df['Embarked'],y=df['Pclass'],color='green')  # same output
plt.show()

year=[2000,2001,2002,2003,2004,2005]
sales_Q1=[10000,20000,40000,60000,80000,90000]
sales_Q2=[12000,8000,90000,62000,82000,92000]

# plotting Boxplot using seaborn
sns.boxplot(data=sales_Q1)
sns.boxenplot(data=sales_Q1)
plt.show()

# Voilin plot shows variance and box plot.
sns.violinplot(data=sales_Q1,color='lightblue')
plt.show()

sns.lineplot(x=sales_Q1,y=sales_Q2,
             linestyle='--',
             marker='D')

sns.scatterplot(x=sales_Q1,y=sales_Q2)

# Relative plot : similar to scatter
sns.relplot(x=sales_Q1,y=sales_Q2)

# regression plot
sns.regplot(x=sales_Q1,y=sales_Q2)

'''
higher the error less is the correlation
'''

# Joint plot
sns.jointplot(x=sales_Q1,y=sales_Q2)

# plt.subplots(2,2) -> subplots(rows,cols)
# plt.subplot(2,2,1) -> chooses 1st plot of subplots
# plt.subplot(2,2,2) -> chooses 2nd plot of subplots
# plt.subplot(2,2,3) -> chooses 3rd plot of subplots
# plt.subplot(2,2,4) -> chooses 4th plot of subplots

plt.figure(figsize=(10,10))
plt.subplots(2,2)
plt.subplot(2,2,1)
plt.plot(year,sales_Q1)

plt.subplot(2,2,2)
plt.plot(year,sales_Q2)

plt.subplot(2,2,3)
sns.boxplot(data=sales_Q1)

plt.subplot(2,2,4)
sns.boxplot(data=sales_Q2)
plt.show()